worker_processes  1;

events { worker_connections  1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile        on;
  keepalive_timeout  65;

  # Docker DNS resolver needed because proxy_pass uses variables ($upstream)
  resolver 127.0.0.11 ipv6=off valid=30s;

  map $host $upstream {
    default "";
    cas.localtest.me     cas:8080;
    grafana.localtest.me grafana:3000;
    prom.localtest.me    prometheus:9090;
    whoami.localtest.me  whoami:80;
  }

  server {
    listen 80;
    server_name cas.localtest.me;

    location / {
      proxy_pass http://cas:8080;
      proxy_http_version 1.1;
      proxy_set_header Host              $host;
      proxy_set_header X-Forwarded-Host  $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Uri   $request_uri;
      proxy_set_header X-Real-IP         $remote_addr;
    }
  }

  server {
    listen 80;
    server_name ~^(.+)\.localtest\.me$;

    if ($upstream = "") { return 404; }

    error_page 401 = @cas_login;

    location @cas_login {
      return 302 http://cas.localtest.me/login?redirect=http://$host$request_uri;
    }

    location = /_auth {
      internal;
      proxy_pass http://cas:8080/auth/verify;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header Cookie $http_cookie;

      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Uri  $request_uri;
      proxy_set_header X-Real-IP        $remote_addr;
      proxy_set_header Host             $host;
    }

    location / {
      auth_request /_auth;

      proxy_pass http://$upstream;
      proxy_http_version 1.1;

      proxy_set_header Host              $host;
      proxy_set_header X-Forwarded-Host  $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Uri   $request_uri;
      proxy_set_header X-Real-IP         $remote_addr;
    }
  }
}
